s = "seehemewe"

print(s[:3])
i = s.index("h")
print(s[i:i+2])
i = s.index("m")
print(s[i:i+2])
i = s.index("w")
print(s[i:i+2])
i = s.index("h")
print(s[i:i+3])
i = s.index("m")
print(s[i:i-3:-1])
i = s.index("w")
print(s[i:i-7:-3])